# Generated by Django 4.1.3 on 2022-12-05 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rename_vehicule_type_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2022, 12, 5, 11, 51, 3, 427455, tzinfo=datetime.timezone.utc)),
        ),
    ]
