# Generated by Django 4.1.3 on 2022-12-05 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rental_return_date_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2022, 12, 5, 12, 6, 40, 392927, tzinfo=datetime.timezone.utc)),
        ),
    ]
