# Generated by Django 4.1.3 on 2022-12-05 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_vehicle_rented_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 13, 17, 43, 990071, tzinfo=datetime.timezone.utc)),
        ),
    ]
