# Generated by Django 4.1.3 on 2022-12-07 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 10, 29, 14, 971209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 10, 29, 14, 969206, tzinfo=datetime.timezone.utc)),
        ),
    ]
