# Generated by Django 4.1.4 on 2023-01-12 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.AlterField(
            model_name='agent',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 1, 33, 1, 346641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_annonce',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 1, 33, 1, 346641, tzinfo=datetime.timezone.utc)),
        ),
    ]
