# Generated by Django 4.1.2 on 2022-10-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.family'),
        ),
    ]
