# Generated by Django 4.1.2 on 2022-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_animal_name_alter_animal_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
