# Generated by Django 4.1.2 on 2022-10-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
