# Generated by Django 4.1.2 on 2022-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
